# Generated by Django 5.1.5 on 2025-02-05 11:43

from django.db import migrations
from django.contrib.auth.models import User
import environ

env = environ.Env()
environ.Env.read_env() 

def create_superuser (app , schema_editor):
    User = app.get_model("auth" , "User")
    if not User.objects.filter(username = "admin").exists():
        password = env('admin_password')
        User.objects.create_superuser("admin", "upret" , password)

class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faq_language'),
    ]

    operations = [
      migrations.RunPython(create_superuser),

    ]
